### ISSUE TITLE
Does this integration still work locally with the lastest Daikin gateway firmware?

### ISSUE THREAD

**Issue by MikeEvans** [tadasdanielius/daikin_altherma#105]
This isn't really the right place to ask this, but I can't think of anywhere better!

Since April, my Onecta app has been offering me a new firmware for my BRP069A61 gateway.  Since this was around the time they changed the authentication methodology for their online API, I thought it was prudent to check that the new firmware doesn't do anything to disrupt the local API which this integration uses.  Can anyone confirm that this integration still works locally when the gateway is updated to the latest firmware (436CC180)

**Comment by mdkeil** [comment]
> Can anyone confirm that this integration still works locally when the gateway is updated to the latest firmware (436CC180)

I can confirm this!

**Comment by MikeEvans** [comment]
> > Can anyone confirm that this integration still works locally when the gateway is updated to the latest firmware (436CC180)
> 
> I can confirm this!

Much appreciated.
