### ISSUE TITLE
Not working for BRP069A78 (Altherma 3)

### ISSUE THREAD

**Issue by clovissix** [tadasdanielius/daikin_altherma#15]
Hi,

I tried installing your component but it doesn't seem to be working for the latest Altherma with a built in network gateway (BRP069A78).  Any help on where I should start looking to fix this error?

<img width="527" alt="Screenshot 2022-01-23 at 02 05 38" src="https://user-images.githubusercontent.com/21120236/150660640-207ab5db-bc33-4668-a7fa-fb7a1af456e7.png">

**Comment by tadasdanielius** [comment]
Hi,

I am not sure if this module has API and can be supported at all. Can you try to connect with your browser?
```
http://192.168.1.155/
https://192.168.1.155/

http://192.168.1.155/mca
```

Can you establish the connection?

**Comment by clovissix** [comment]
Hi Tadas,

Thank you for the quick response.
I get a File not found:
![image](https://user-images.githubusercontent.com/21120236/150852303-6ee0c056-04ec-498b-b840-e8c2fb978edf.png)

**Comment by clovissix** [comment]
It must have some sort of api since I can connect with my Daikin app to it. Installation was much the same as my Daikin Airco's.

**Comment by tadasdanielius** [comment]
Probably the protocol is different compared to brp069a6x. I looked at [this](https://bitbucket.org/mustang51/pydaikin/src/master/) repo and the way it communicates with the device seems very different. Maybe you can try to open this url `http://192.168.1.155/common/basic_info` (I am just trying to guess endpoints from [here](https://bitbucket.org/mustang51/pydaikin/src/b3b7878c8f411b26c21c21dc08818cf8af5ec6c6/pydaikin/daikin_brp069.py#lines-67) 

BTW, do you connect directly to the unit or over the cloud. If you use Daikin Residential Contoller app you may try [daikin_residential_brp069a62](https://github.com/BigFoot2020/daikin_residential_brp069a62) integration.

**Comment by clovissix** [comment]
Oh, thx! I'll check that out.
