### ISSUE TITLE
Unit detected - Configuration failed - missed Model Number?

### ISSUE THREAD

**Issue by Bettinaglio** [tadasdanielius/daikin_altherma#16]
Good Morning Tadas 

I've a Daikin Lan Controller BRP069A61 (same as BRP069A62 but no Grid) and tried to activate your custom component. It does recognise the unit and invited me to configure it,  what i did. Result (Daikin HVAC controller (173300342) - Configuration failed, ):

![ScreenShot 2022-02-01 alle 07 05 36](https://user-images.githubusercontent.com/40548048/151920511-03ae82f8-602d-47df-9021-59bd7056bac3.png)

The following is the error registered:
-START-
Dettagli registro (ERRORE)

Questo errore ha avuto origine da un'integrazione personalizzata.
Logger: homeassistant.config_entries
Source: custom_components/daikin_altherma/__init__.py:210 
Integration: Daikin Altherma HVAC (documentation, issues) 
First occurred: 06:53:07 (1 occurrences) 
Last logged: 06:53:07

Error setting up entry Daikin HVAC controller (173300342) for daikin_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/daikin_altherma/__init__.py", line 53, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = api = await setup_api_instance(
  File "/config/custom_components/daikin_altherma/__init__.py", line 32, in setup_api_instance
    await api.api_init()
  File "/config/custom_components/daikin_altherma/__init__.py", line 134, in api_init
    await self.get_HWT_device_info()
  File "/config/custom_components/daikin_altherma/__init__.py", line 210, in get_HWT_device_info
    "model": await hwt.model_number,
AttributeError: 'NoneType' object has no attribute 'model_number'
-END-
Is there anything I can do to overcame the mission model number in the unit?

Your integration seems to make exactly what I need (while in other integration wich recognise the unit  as BRP069A62 i can not set the target temperature (as I can in the Altherma App on the iPhone).

Thanks for your support and your component.
Louis

**Comment by tadasdanielius** [comment]
Hi, this is strange. Do you have hot water tank or just space heating? What is your daikin device model?

**Comment by tadasdanielius** [comment]
I have put pre-release (v1.1.3 version) which should address this issue. Would be good if you could try it. Let me know if you encounter any problems.

**Comment by Bettinaglio** [comment]
Tadas, you are just amazing! Sorry for the delay in answering; the unit (Lan Adapter) is a RBRP069A61 and its handling an Daikin/Rotex Hyprid RHYKOMB33AA Central Heating (which is a combination of a Daikin Gas Heater 33 Kw (in my case without warm water tank) and a Daikin HeatPump 5 Kw (suitable for “not floor” heating in older buildings).

I installed the new version, cancelled the integration and HA did recognise the unit without any hesitation, super integration, thanks a lot (pizza and red vine is waiting here!).



Do you think there is a way on having an “App simil” representation (like the HA climate lovelace card)?




I wish you a good and successful day and a happy week end.

----------------------------------------------------
Louis A. Bettinaglio
Via Lombardia 87, Corgeno  
I - 21029 Vergiate VA    
Tel: (39) 0331-948 538 
Fax: (39) 0331-948 898
***@***.***
----------------------------------------------------
Questo messaggio e gli allegati possono contenere informazioni riservate esclusivamente al destinatario. Il ricevente, se diverso dal destinatario è avvertito che qualunque utilizzo, divulgazione o copia  di questa comunicazione comporta violazione delle disposizioni di legge sulla tutela dei dati personali ed è pertanto rigorosamente vietata. Qualora il presente messaggio sia stato ricevuto per errore, Vi prego di informarmi immediatamente via e-mail a ***@***.***

This e-mail and any files transmitted with it are confidential and may be privileged and are intended solely for the use of the individual or entity to whom they are addressed. Any unauthorised direct or indirect dissemination or copyng of this message and any attachments are strictly prohibited. If you have received the e-mail in error please inform me by e-mail to ***@***.***

**Comment by tadasdanielius** [comment]
Hi, that's great it worked  🍕 :wine_glass: thanks for confirming.
Yes indeed, you can have HA climate lovelace card. Like I described in README, just open your `configuration.yaml` file and add the following details there:

```yaml
climate:
  - platform: generic_thermostat
    name: My thermostat
    unique_id: daikin_climate_control
    target_sensor: sensor.indoor_temperature
    min_temp: 18
    max_temp: 26
    heater: switch.climate_control
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    ac_mode: false
    initial_hvac_mode: "heat"
    min_cycle_duration:
      seconds: 5
```
and restart your HA instance.

Few things you might want to change for example `target_sensor` you are not limited to use daikin's temperature sensor but any other temperature connected to home assistant you have in your home, and some other parameters like tolerance levels, initial `target_temp` etc. You can read more about it in [generic_thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)

Let me know if you experience any problems.

**Comment by Bettinaglio** [comment]
Super, Tadas, works like a charme…. the only thing I have to do now is to calibrate (set up temp. of the new thermostate (the Daikin control panel at the inside wall) and the heating panel thermostate (actual a MAX! in future a Fritz Dect 301) ore using directly the panel thermostate. Thanks a world for your super work. Greetings from Italy.



----------------------------------------------------
Louis A. Bettinaglio
Via Lombardia 87, Corgeno  
I - 21029 Vergiate VA    
Tel: (39) 0331-948 538 
Fax: (39) 0331-948 898
***@***.***
----------------------------------------------------
Questo messaggio e gli allegati possono contenere informazioni riservate esclusivamente al destinatario. Il ricevente, se diverso dal destinatario è avvertito che qualunque utilizzo, divulgazione o copia  di questa comunicazione comporta violazione delle disposizioni di legge sulla tutela dei dati personali ed è pertanto rigorosamente vietata. Qualora il presente messaggio sia stato ricevuto per errore, Vi prego di informarmi immediatamente via e-mail a ***@***.***

This e-mail and any files transmitted with it are confidential and may be privileged and are intended solely for the use of the individual or entity to whom they are addressed. Any unauthorised direct or indirect dissemination or copyng of this message and any attachments are strictly prohibited. If you have received the e-mail in error please inform me by e-mail to ***@***.***
