### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by weado** [tadasdanielius/daikin_altherma#19]
Hello, 
After installed the component with HACS, restart my HA, any new integration with the name "Daikin Altherma HVAC" display. How can I add my new AC with this component ?  I didn't find this information on the README 

Thanks a lot

HA : 2021.12.5
Daikin Altherma HVAC : 1.1.3

**Comment by tadasdanielius** [comment]
Hi, Normally it should discover automatically. You should find in HA Integrations page. If it's not, then you can click on add integration and search for Daikin Altherma HVAC. You may need to enter IP address of you daikin device.
