### ISSUE TITLE
entities not showing up in overview

### ISSUE THREAD

**Issue by johansmeets** [tadasdanielius/daikin_altherma#20]
Hi,

I was able to install this extension via HACS. My Daikin Heat Pump with BRP069A61 gateway was automatically detected and I was able to configure the integration. 
However, none of the entities show up in my overview page, although they are all enabled. I can't seem to find out what I'm doing wrong here? Never had this issue with other integrations.

Kind regards,
johan

**Comment by johansmeets** [comment]
I found an error log concerning this problem, which states the following. 
Can anyone conclude something from this?

_Logger: homeassistant.components.number
Source: custom_components/daikin_altherma/number.py:46
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 6:22:44 PM (2 occurrences)
Last logged: 6:22:44 PM

Error adding entities for domain number with platform daikin_altherma
Error while setting up daikin_altherma platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
    ATTR_MIN: self.min_value,
  File "/config/custom_components/daikin_altherma/number.py", line 46, in min_value
    return config['minValue']
KeyError: 'minValue'_

**Comment by tadasdanielius** [comment]
Hi, what is the model of your heat pump? Does it has boiler?

**Comment by johansmeets** [comment]
Hi,

I have a Daikin Altherma 3 heat pump with built-in boiler.
The specific model is:

Indoor unit: EHVX08S23DJ6V
Outdoor unit: ERGA06DAV3

**Comment by tadasdanielius** [comment]
Seems like your unit has different profile structure. I will add additional logging to see how it differs

**Comment by tadasdanielius** [comment]
I have published pre-release version which should save some diagnostic info, mainly unit profiles. If you are using [HACS](https://hacs.xyz/) then install again or redownload the repo. Make sure the `Show beta versions` is checked and select [v.1.1.4](https://github.com/tadasdanielius/daikin_altherma/releases/tag/v.1.1.4) version. Restart home assistant and you should find few files (daikin_altherma_0.json, daikin_altherma_1.json, daikin_altherma_2.json, ...) in your /config folder. 
Files contains unit profile info. That should help to understand how the profile is organized  on your device. As an example here is what you should expect:

```json
{
  "SyncStatus": "update",
  "Sensor": [
    "IndoorTemperature",
    "OutdoorTemperature",
    "LeavingWaterTemperatureCurrent"
  ],
  "UnitStatus": [
    "ErrorState",
    "InstallerState",
    "WarningState",
    "EmergencyState",
    "TargetTemperatureOverruledState"
  ],
  "Operation": {
    "Power": ["on", "standby"],
    "OperationMode": ["heating", "cooling", "auto"],
    "LeavingWaterTemperatureCooling": {
      "maxValue": 22,
      "minValue": 5,
      "stepValue": 1,
      "settable": true
    },
    "LeavingWaterTemperatureAuto": {
      "maxValue": 22,
      "minValue": 5,
      "stepValue": 1,
      "settable": false
    },
    "LeavingWaterTemperatureOffsetHeating": {
      "maxValue": 10,
      "minValue": -10,
      "stepValue": 1,
      "settable": true
    },
    "LeavingWaterTemperatureOffsetCooling": {
      "maxValue": 10,
      "minValue": -10,
      "stepValue": 1,
      "settable": false
    },
    "LeavingWaterTemperatureOffsetAuto": {
      "maxValue": 10,
      "minValue": -10,
      "stepValue": 1,
      "settable": true
    }
  },
  "Schedule": {},
  "Consumption": {
    "Electrical": {
      "unit": "kWh",
      "Heating": {
        "Daily": { "contentCount": 24, "resolution": 2 },
        "Weekly": { "contentCount": 14, "resolution": 1 },
        "Monthly": { "contentCount": 24, "resolution": 1 }
      },
      "Cooling": {
        "Daily": { "contentCount": 24, "resolution": 2 },
        "Weekly": { "contentCount": 14, "resolution": 1 },
        "Monthly": { "contentCount": 24, "resolution": 1 }
      }
    }
  }
}

```

**Comment by colseven** [comment]
You have the SD-WLAN Adpater BRP069A78, i think thats the problem or will this work too?

**Comment by johansmeets** [comment]
Hi, thanks for reaching out and helping me.

I've installed your new beta version v1.1.4.

But when looking in the files (daikin_altherma_0.json, daikin_altherma_1.json, daikin_altherma_2.json, ...) in my /config folder, there is not much to see...
All it says is:

{"SyncStatus": "reboot", "UnitStatus": ["ErrorState"], "DateTime": {"DateTimeAdjustable": false}}

**Comment by tadasdanielius** [comment]
Like @colseven said you are probably using SD-WLAN adapter. Is your unit connected to the network via wifi? I think it is not possible to control the unit with this device in this way.

**Comment by tadasdanielius** [comment]
Can you control your device with Daikin's app remotely?

**Comment by johansmeets** [comment]
Hi, yes I can control the unit remotely with the Daikin app , without any problem.

**Comment by tadasdanielius** [comment]
Strange, maybe you have old firmware on your gateway...

**Comment by colseven** [comment]
Newest Firmware - everything works fine, i Need just a setpoint change for the Tank like heating Mode, that works Fine.

![CFA11234-2F0C-4B99-B500-32AF8C0F1B8B](https://user-images.githubusercontent.com/63189272/200840222-7f8ee32a-b339-4a60-b8c0-1e679693d920.png)
![F854BE9C-D45D-4B58-8519-1BBB0A244499](https://user-images.githubusercontent.com/63189272/200840243-c5eafdf7-d296-4de5-b91a-dfa974ac1a98.png)
