### ISSUE TITLE
"Add-on config 'startup' with 'before' is deprecated"

### ISSUE THREAD

**Issue by Bettinaglio** [tadasdanielius/daikin_altherma#21]
Have this message in the HA Supervisor log: (not sure if it belongs to this integration)

22-03-11 06:00:42 WARNING (SyncWorker_5) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Daikin MQTT connector
22-03-11 06:00:42 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Daikin MQTT connector

Thanks and enjoy the day.
Louis

**Comment by tadasdanielius** [comment]
Seems like from another daikin integrations.
