### ISSUE TITLE
No device shows up

### ISSUE THREAD

**Issue by inakifeliu** [tadasdanielius/daikin_altherma#26]
Hi, 

After installing it, nothing shows up, I found this in the registry:

_Logger: homeassistant.config_entries
Source: config_entries.py:537
First occurred: 14:28:16 (1 occurrences)
Last logged: 14:28:16

Error occurred loading configuration flow for integration daikin_altherma: cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)_

Any help is appreciated,

Iñaki

**Comment by tadasdanielius** [comment]
Something is not right with HA installation. Which version of Home assistant you are using?

**Comment by inakifeliu** [comment]
## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.86
arch | x86_64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.10.1
Stage | running
Available Repositories | 1112
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2022.05.3
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 5.9 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Samba share (9.3.0), Check Home
Assistant configuration (3.10.2), Terminal & SSH (8.10.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 1

</details>

El dl., 13 de juny 2022, 17:38, Tadas Danielius ***@***.***>
va escriure:

**Comment by tadasdanielius** [comment]
That is very old. You should upgrade you HA to the latest version.

**Comment by inakifeliu** [comment]
You we're right, It was a old HA version issue...

Thank you!!!
