### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by giakko1982** [tadasdanielius/daikin_altherma#28]
Hi, i have brp069a61 controller. This work fine and i've just integrated in HA.
I can not find power consumption sensor
<img width="1055" alt="Schermata 2022-07-04 alle 21 19 59" src="https://user-images.githubusercontent.com/75729969/177208293-b3dd94d9-fe33-4543-a4c0-ce7de63479bc.png">
Can you help me?!

**Comment by tadasdanielius** [comment]
I think the problem is that your device is mixed. I mean with gas and electricity. I don't have access to such type of device for experimentation so your help is needed in order to try to fix that. First of all check the logs for warning messages something like similar like `consumption information could not be added` or any error messages related to daikin_altherma. Next, with file editor go to `config/custom_components/daikin_altherma` and look for file `__init__.py` then go to the line (probably 37) and change from:

```
    # Uncomment this if you want to store profile info in json files.
    #try:
    #    for profile in unit_profiles:
    #        filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
    #        with open(filepath, 'w') as f:
    #            f.write(json.dumps(profile['profile']))
    #except Exception as e:
    #    _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)
```
 change to:

```
    # Uncomment this if you want to store profile info in json files.
    try:
        for profile in unit_profiles:
            filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
            with open(filepath, 'w') as f:
                f.write(json.dumps(profile['profile']))
    except Exception as e:
        _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)

Restart you home assistant and then look in the config folder for files `daikin_altherma_*.json`. Post your content here so we can look into your device configuration.

**Comment by giakko1982** [comment]
`{"SyncStatus": "update", "Sensor": ["IndoorTemperature", "OutdoorTemperature", "LeavingWaterTemperatureCurrent"], "UnitStatus": ["ErrorState", "InstallerState", "WarningState", "EmergencyState", "TargetTemperatureOverruledState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating"], "TargetTemperature": {"heating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 0.5}}, "RoomTemperatureHeating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 0.5, "settable": true}, "LeavingWaterTemperatureHeating": {"maxValue": 70, "minValue": 25, "stepValue": 1, "settable": true}}, "Schedule": {"Base": "action", "defaultScheduleAvailable": "true", "NameAdjustable": "false", "List": {"heating": [{"StartTime": {"stepValue": 10.0, "unit": "minutes"}, "TargetTemperature": {"heating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 1}}, "Actions": ["StartTime", "TargetTemperature"], "maxActionsAllowed": 6}, ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], []]}}}`

this is content file daikin_altherma_*.json

**Comment by tadasdanielius** [comment]
It looks like your device does not provide any details about power consumption. Do you see it in official daikin app?

**Comment by giakko1982** [comment]
No, in official app i don't see it

Il mar 16 ago 2022, 14:45 Tadas Danielius ***@***.***> ha
scritto:

**Comment by robsonke** [comment]
I face the same problem. The device doesn't support it but it feels strange. On my wall thermostat I can see the overal usage in kWh's and I'm also using the ESPAltherma integration which gives me Current and Voltage numbers as well. Like they hide it on purpose.

**Comment by giakko1982** [comment]
That's weird.
------------------------------
Giacomo Solitario
Mobile +393292956833


[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 22 ago 2022 alle ore 09:09 Rob Sonke ***@***.***>
ha scritto:

**Comment by Arnold-n** [comment]
> I face the same problem. The device doesn't support it but it feels strange. On my wall thermostat I can see the overal usage in kWh's and I'm also using the ESPAltherma integration which gives me Current and Voltage numbers as well. Like they hide it on purpose.

ESPAltherma can show voltage and current because these measurements are available through the X10A connector. The brp069a61 connects through P1/P2 which to my knowledge does not contain voltage or current information.

The kWh's are communicated via P1/P2 but only when explicitly requested by the wall thermostat (in my case: when manually requested, or at the end of each month for the monthly statistics).

**Comment by giakko1982** [comment]
I've solved installing Power Meter 😁

Il mar 23 ago 2022, 19:45 Arnold ***@***.***> ha scritto:

**Comment by robsonke** [comment]
Any of you also know what the difference is between the primary and secondary Current? Should we sum those up for the power usage? I can't really relate it to my overall power usage.

**Comment by tadasdanielius** [comment]
AFAIK, the primary is from the mains it is what you plug into your socket. The secondary is from the inverter to the compresor. While primary has higher voltage (should be around 230V) and lower amps, the secondary has lower voltage but higher amps.
One of the problem with measuring electricity consumption is that (I believe) does not include electric heating of hot water tank. What it gives is just the pump consumption, but if the water is heated without fans it won't be accounted. So, I somehow get lower values for hot water tank.
