### ISSUE TITLE
Calculating COP

### ISSUE THREAD

**Issue by Shogun1978** [tadasdanielius/daikin_altherma#41]
Hello,
I am using this integration since a few months and I am very happy with it, works absolutely perfect! I love the fact that it's not using the cloud and through all HA updates, the integration still works.
So I would like to ask for an enhancement. As in this github project documented, the COP can be calculated:

https://github.com/raomin/ESPAltherma

The calculation is already documented, what you need is some additional values from the heat pump. As it seems, the values are exported on the github project with an ESP. I don't know, if the Daikin LAN adapter also exports this information. But if yes, it would be great to see the additional sensor values and a calculated COP.

As I am not a programmer, I am not capable of doing it myself, but would be glad to see this enhancement - if possible.

Regards,
Harald

**Comment by tarmor1** [comment]
Hi Harald!
If you open your LAN adapter data from Onecta app in smartphone (their cloud service) - do you see there consumption and production data?
Many of Altherma models (at least the one I do have) do not publish to LAN adapter any energy productuon/consumption data so nothing to calculate.
I myself run ESPAltherma as well in addition and look for the COP there.

**Comment by Shogun1978** [comment]
Unfortunately, I don't see this data in the app. It seems that they don't export this data to the app :-( So seems like there is no chance to get the l/h and so the COP?

**Comment by tarmor1** [comment]
Yes, if it's not in the app, your Altherma does not export it to LAN adapter and it's not visible in Dainius' component.
New firmware releases could change it, but given that Altherma2 that likely you and I both have is already an old model, so I wouldn't keep my hopes up the changes coming there.
If you like detailed metering and graphs (incl COP), ESPAltherma is needed. Both this component and ESPAltherma run together just fine and installing the ESP32 and flashing it according to ESPAltherma Wiki was really straightforward.

**Comment by Shogun1978** [comment]
I have a brand new Altherma 3 Geo, but the values are not exported to the app. Not even to the Zennio KNX adapter. I talked to the phone support today, but they also said that this is not visible. So ESPAltherma or waiting for a firmware update. I already asked them to implement these values. Besides the "consumed power" it would be great to know the "generated heat in kWh" what is visible on the display itself when you are in front of the heat pump. So the value is already there. Would be great so that you can frequently take a look and if the heat pump COP is below the expected value for the system (in my case 2-3 would be bad, everything above 4 is good) you get notified to contact your local support company to adjust the settings.

Anyway: thanks for the fast response and the great integration! :-)

**Comment by tarmor1** [comment]
Hi!
Looks indeed promising as this is a new device, congrats! What you could try - in case you're an Apple guy, run the newest Onecta beta with TestFlight (some Apple programme that enables you to be Beta tester). I get Onecta betas to my iPhone and consequently, it pushes out the Firmwares together with new app. You could try that. No clue how it's done on Android.
All in all, Daikin is quiet about their delivery plans and API documentation type of things, at least on the Altherma family. Most of the information about how to access their devices is reverse engineered by the home automation community.

As for the COP, and eg in my case, the value can be quite jumpy, as depending on the temperature and the defrost cycle there is no constant value, at least the sensor config I stole from ESPAltherma Wiki.
An example:
![image](https://user-images.githubusercontent.com/106139715/195523474-15fb32ea-e1f5-4fe6-a2a0-cabb4cfec907.png)
The peaks come from the defrost, as here in Estonia where I live this night was already a bit cold.
But what's great about HA sensors is you can config them IF-ELSE to remove those jumps. Jumps aside, it averages today for me to COP 3.5.

**Comment by Shogun1978** [comment]
Hey,
as I am an Android guy, I can't get a beta as it seems (the app store and the app itself don't offer anything to test). The bumps in the COP seems to be the reason why they don't want to share that in the app or even the UI of the Altherma itself. Currenty, we have could nights and relatively warm days. I live in Germany, so we have between 0 degrees at night and 15-20 degrees at day time... that is kind of killing a good COP. On some days, I have a COP of 4-5, on bad days it's close to 1 - at least from the values I can eastimate from the display on the heat pump. When you have a cold day, the daily consumed energy is about 10 and the generated heat about 50 kWh. On the next day, it's warmer and so the consumed energy is about 7 and the generated heat is due to the scale of the graph maybe 25 or 28 or 30 - or 24? You can't really see that.

I don't want to play around with the ESPAltherma project directly on the heat pump. So I must wait till Daikin gets something official out for customers.
Thanks for you support! I will close the ticket :-)
