### ISSUE TITLE
Request update "Heating Energy" sensors D2CND

### ISSUE THREAD

**Issue by eduardkirkosa** [tadasdanielius/daikin_altherma#46]
Hi, @tadasdanielius 

Could you please update the "Heating Energy" sensors  for D2CND ( via DRGATEWAYAA ) the device_class/state_class, so' I can add it to Energy Dashboard (  Gas Consumption ).
Thanks,
Edy

**Comment by tadasdanielius** [comment]
Fixed in [v1.3.7](https://github.com/tadasdanielius/daikin_altherma/tree/v1.3.7)

**Comment by eduardkirkosa** [comment]
Thanks :) working

![image](https://user-images.githubusercontent.com/45036652/206678971-b0ca537f-da94-4fbd-b755-34e71ff677dc.png)

![image](https://user-images.githubusercontent.com/45036652/206679034-e807961d-eeb9-4799-8c4e-abeef32b766a.png)

**Comment by tadasdanielius** [comment]
12kWh electricity consumption. You must be paying a fortune for electricity 😄

**Comment by eduardkirkosa** [comment]
hope not ;) - i still wait for the bill on November ;)
75%+ it's the dmn HeatPump :( 

![image](https://user-images.githubusercontent.com/45036652/206688092-414a13bd-4a3e-469c-b8c2-019c20a30db6.png)

**Comment by tadasdanielius** [comment]
You must be heating football stadium if it takes 75% of the 12kWh. If I see 20kWh/day (only for heatpump) I am already freaking out. Overall my total consumption looks a bit higher (~800kWh) for Nov.

**Comment by eduardkirkosa** [comment]
Combo combination : Poor(I think) isolation from windows + doors + attic , radiators (not underfloor) , pets (1 door sometimes open for long time) , I bet in January the external part of the HP will take off like a helicopter :))))))))))

**Comment by eduardkirkosa** [comment]
Hi @tadasdanielius 

I turn on the D2CND to check how it's working, and the values for "Heating Energy" stay at "0 kwh" - something it's weird :(
![image](https://user-images.githubusercontent.com/45036652/207253499-ac2a9f32-ed30-45b0-8f3e-7190bc7f61c4.png)

![image](https://user-images.githubusercontent.com/45036652/207253793-238650b4-7cb6-4f58-87a6-d031a18d01ce.png)
![image](https://user-images.githubusercontent.com/45036652/207253872-dac41816-e6b3-4f5a-8bf8-c8bc2bc103b4.png)
![image](https://user-images.githubusercontent.com/45036652/207253929-4b4c2929-8d48-4f43-b401-94df8c9f26d6.png)

And from the App:
![image](https://user-images.githubusercontent.com/45036652/207253689-a4dcabd3-f373-4f88-aaf6-5ab20976647d.png)

If more info/logs are needed just point me to the right location and i try get it :)

Thanks,
Edy

**Comment by eduardkirkosa** [comment]
for HP works

![image](https://user-images.githubusercontent.com/45036652/207274641-7b69d4ab-58a0-4cd9-9f54-20ddc3210e3b.png)

**Comment by eduardkirkosa** [comment]
HP
![image](https://user-images.githubusercontent.com/45036652/207280332-9d759643-1092-4b5e-8904-7dacb3d35fae.png)

**Comment by eduardkirkosa** [comment]
Looks like the D2CND has both options for Energy "gas + electricity" - and your sensor pick up the "electricity"
![image](https://user-images.githubusercontent.com/45036652/207789430-f27cb3c2-652d-49a6-94e4-360c3db81efe.png)
![image](https://user-images.githubusercontent.com/45036652/207789682-dcc3891c-1302-458b-a6f2-8381187baeca.png)

for sure the energy "gas" has different source

**Comment by tadasdanielius** [comment]
Yes, Gas has separate values but at the moment they are not being used as I don't have gas device therefore I don't see them.

**Comment by eduardkirkosa** [comment]
can I / it's possible - to get out some logs/events that you can use ?

**Comment by tadasdanielius** [comment]
if you can drop a [profiles](https://github.com/tadasdanielius/daikin_altherma/issues/28#issuecomment-1176208409) of your devices then I might be able to implement, but can't promise anything 😄

**Comment by arildas** [comment]
I think the best way is to log debug real info with original app to zip file. Run it for linger time to cillect more data.
![C3566D74-A6EB-44EE-86EB-B765D7B7BCF5](https://user-images.githubusercontent.com/36076493/207920556-be59cc33-baf4-4d07-9fb5-fb9ace9e0ed5.jpeg)

**Comment by eduardkirkosa** [comment]
@tadasdanielius i did the steps for profiles and i get now:
![image](https://user-images.githubusercontent.com/45036652/208233906-a44a8f58-2632-47cd-a8f9-b6d0abc3998e.png)

![image](https://user-images.githubusercontent.com/45036652/208233914-64b8ec7f-2a15-4534-a6b2-c32019eea02c.png)

![image](https://user-images.githubusercontent.com/45036652/208233926-b046e8ea-194a-483c-8fdc-1fd1df872ce5.png)

**Comment by tadasdanielius** [comment]
You probably changed something too much. You just need to remove # from those lines in \_\_init\_\_.py

<img width="985" alt="image" src="https://user-images.githubusercontent.com/8099860/208261752-13f9138a-446e-4716-90f1-fe776b91b229.png">

It should look like this
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8099860/208262234-63955de9-2116-41e9-8593-5c1baf4bd29f.png">

**Comment by eduardkirkosa** [comment]
/config/daikin_altherma_0.json
{"SyncStatus": "reboot", "UnitStatus": ["ErrorState"], "DateTime": {"DateTimeAdjustable": false}}

/config/daikin_altherma_1.json
{"SyncStatus": "update", "Sensor": ["IndoorTemperature", "OutdoorTemperature", "LeavingWaterTemperatureCurrent"], "UnitStatus": ["ErrorState", "InstallerState", "WarningState", "EmergencyState", "TargetTemperatureOverruledState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating"], "TargetTemperature": {"heating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 0.5}}, "RoomTemperatureHeating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 0.5, "settable": true}, "LeavingWaterTemperatureOffsetHeating": {"maxValue": 10, "minValue": -10, "stepValue": 1, "settable": true}}, "Schedule": {"Base": "action", "defaultScheduleAvailable": "true", "NameAdjustable": "false", "List": {"heating": [{"StartTime": {"stepValue": 10.0, "unit": "minutes"}, "TargetTemperature": {"heating": {"maxValue": 30.0, "minValue": 12.0, "stepValue": 1}}, "Actions": ["StartTime", "TargetTemperature"], "maxActionsAllowed": 6}, ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], []]}}, "Consumption": {"Electrical": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}}}

/config/daikin_altherma_2.json
{"SyncStatus": "update", "Sensor": ["TankTemperature"], "UnitStatus": ["ErrorState", "InstallerState", "WeatherDependentState", "WarningState", "EmergencyState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating"], "TargetTemperature": {"heating": {"maxValue": 60.0, "minValue": 30.0, "stepValue": 0.5}}, "DomesticHotWaterTemperatureHeating": {"maxValue": 60.0, "minValue": 30.0, "stepValue": 1.0, "settable": true}, "powerful": ["0", "1"]}, "Schedule": {}, "Consumption": {"Electrical": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}}}

**Comment by eduardkirkosa** [comment]
The - error state it's due to stupid 60gr tank water clean/cycle blabla - that i stopped.

**Comment by tadasdanielius** [comment]
Nothing related to gas usage to pick it up. Do you have two separate devices?

**Comment by eduardkirkosa** [comment]
Hi, yes
![image](https://user-images.githubusercontent.com/45036652/208356089-492b92d3-d72e-4eba-b283-44f7b03d989c.png)

**Comment by tadasdanielius** [comment]
I see. Can you temporary disable Daikin Altherma and leave only GazBoiler restart HA, copy files and then you can enable it again. The reason is that they both write to the same files and apparently Daikin Altherma overrides the GazBoiler

**Comment by eduardkirkosa** [comment]
**daikin_altherma_0.json**
{"SyncStatus": "registration", "UnitStatus": ["ErrorState"], "DateTime": {"DateTimeAdjustable": true}}

**daikin_altherma_1.json**
{"SyncStatus": "update", "Sensor": ["IndoorTemperature"], "UnitStatus": ["ErrorState", "WarningState", "TargetTemperatureOverruledState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating_day", "heating_night"], "SensorTemperature": {"stepValue": 0.5}, "TargetTemperatureDay": {"maxValue": 30.0, "minValue": 10.0, "stepValue": 0.5}, "TargetTemperatureNight": {"maxValue": 30.0, "minValue": 10.0, "stepValue": 0.5}, "TargetTemperature": {"heating_day": {"maxValue": 30.0, "minValue": 10.0, "stepValue": 0.5}, "heating_night": {"maxValue": 30.0, "minValue": 10.0, "stepValue": 0.5}}, "EcoMode": ["0", "1"]}, "Schedule": {"Base": "TimeSegment", "defaultScheduleAvailable": "false", "NameAdjustable": "false", "List": {"Heating": [{"StartTime": {"stepValue": 15, "unit": "minute"}, "EndTime": {"stepValue": 15, "unit": "minute"}, "OperationMode": ["heating_day", "heating_night"], "TargetTemperature": {"heating_day": {"maxValue": 21.0, "minValue": 21.0, "stepValue": 0.0}, "heating_night": {"maxValue": 21.0, "minValue": 21.0, "stepValue": 0.0}}, "TimeSegment": ["StartTime", "EndTime"], "MaxSegmentsAllowed": 3}, [], ["weekday", "weekend"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]]}}, "Consumption": {"Electrical": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}, "Gas": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}}}

**daikin_altherma_2.json**
{"SyncStatus": "update", "Sensor": ["TankTemperature"], "UnitStatus": ["ErrorState", "WarningState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating", "standby"], "SensorTemperature": {"stepValue": 1.0}, "TargetTemperature": {"heating": {"maxValue": 60.0, "minValue": 35.0, "stepValue": 1.0}, "standby": {"maxValue": 60.0, "minValue": 35.0, "stepValue": 1.0}}, "DomesticHotWaterTemperatureHeating": {"maxValue": 60.0, "minValue": 35.0, "stepValue": 1.0, "settable": true}}, "Schedule": {"Base": "TimeSegment", "defaultScheduleAvailable": "false", "NameAdjustable": "false", "List": {"Heating": [{"StartTime": {"unit": "minute"}, "EndTime": {"unit": "minute"}, "OperationMode": ["heating"], "TimeSegment": ["StartTime", "EndTime"], "MaxSegmentsAllowed": 3}, [], ["weekday", "weekend"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["weekday", "weekend"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]]}}, "Consumption": {"Electrical": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}, "Gas": {"unit": "kWh", "Heating": {"Daily": {"contentCount": 24, "resolution": 2}, "Weekly": {"contentCount": 14, "resolution": 1}, "Monthly": {"contentCount": 24, "resolution": 1}}}}}

**Comment by tadasdanielius** [comment]
Can you try to replace `sensor.py` file, located in your `config` folder `custom_components/daiking_altherma` with [this](https://raw.githubusercontent.com/tadasdanielius/daikin_altherma/51-support-gas-consumption/custom_components/daikin_altherma/sensor.py) one.

**Comment by eduardkirkosa** [comment]
Good morning, done

1st logs:
![image](https://user-images.githubusercontent.com/45036652/208833117-5f4024c3-6728-46fb-b4db-e2fcad9bef43.png)

2nd sensors appear for D2CND(Gas):
![image](https://user-images.githubusercontent.com/45036652/208833356-33dd7aef-690e-4e17-ba79-30bcfcc49710.png)

![image](https://user-images.githubusercontent.com/45036652/208833478-6c2d4ab8-f2b1-459d-a701-55a4019bac14.png)
![image](https://user-images.githubusercontent.com/45036652/208833514-34aa10ea-99d7-45ae-909c-5670c8f7551e.png)
![image](https://user-images.githubusercontent.com/45036652/208833313-ac8189cd-9dfc-4036-8a3b-e54549436c76.png)

**Comment by tadasdanielius** [comment]
That's not bad. Now try to replace with [this](https://raw.githubusercontent.com/tadasdanielius/daikin_altherma/51-support-gas-consumption/custom_components/daikin_altherma/sensor.py)

**Comment by eduardkirkosa** [comment]
![image](https://user-images.githubusercontent.com/45036652/208855243-426d9a72-81e6-4c4e-ac2b-6e8ebfd996da.png)

**Comment by tadasdanielius** [comment]
Ok that was a stupid mistake. Let's try again with [this](https://raw.githubusercontent.com/tadasdanielius/daikin_altherma/51-support-gas-consumption/custom_components/daikin_altherma/sensor.py)

**Comment by eduardkirkosa** [comment]
Sensor are back ;)

![image](https://user-images.githubusercontent.com/45036652/208878560-96039e3d-ca63-413a-8b66-416492619e9d.png)
![image](https://user-images.githubusercontent.com/45036652/208878629-de5e3fa0-6e62-4e02-b397-37205cda44af.png)

and no errors in HA logs regarding daikin :) 

Thanks,

**Comment by eduardkirkosa** [comment]
what I can see a bit odd ;), maybe it's History logging slow, but the Value for the sensor show zero and attributes show data ( 2Hours and Day):

![image](https://user-images.githubusercontent.com/45036652/208896880-f7f0dcc6-e20f-477f-b66c-44ec90958f18.png)
![image](https://user-images.githubusercontent.com/45036652/208897025-49821b45-015f-4569-a014-22aa17d72bca.png)

Month show value + attributes
![image](https://user-images.githubusercontent.com/45036652/208897109-d18b67c7-3cb6-4d30-8590-8c77d4d05a10.png)

**Comment by tadasdanielius** [comment]
I see what is happening here. Normally, on my device, the data arrives with values and then is set to null for the rest of the day. This means I can simply pick the last non-null value and set it as the sensor value. However, in your case, the values are being set to 0, which is causing confusion with the integration. It might be best for you to create a template sensor that checks the time of day and picks the correct value from the attribute values. I will think about it.
