### ISSUE TITLE
Compressor state working for Space or DHW

### ISSUE THREAD

**Issue by mxilievski** [tadasdanielius/daikin_altherma#50]
Is there a way to see whether the compressor is active for Space heating or DHW?

Not an issue, just a question. Im gonna put a PR if the API supports this.

**Comment by tadasdanielius** [comment]
I don't think this info can be retrieved via API. One way to get that out is to use [ESPAltherma](https://github.com/raomin/ESPAltherma)

**Comment by mxilievski** [comment]
Tnx @tadasdanielius. Closing this.
