### ISSUE TITLE
ERROR: unable to connect

### ISSUE THREAD

**Issue by palecs** [tadasdanielius/daikin_altherma#65]
Hello Im trying to find best integratio for Daikin altherma and integration with HA for automation. I have downloaded your integration, but when Im try to connect by putting IP information is: `Unable to connect`.

Version of Altherma is: BRP069A78, firmware is 3.2.4 and WiFi module BRP069A78 . 

thank you for any suggestions.

**Comment by tadasdanielius** [comment]
BRP069A78  is not supported. I am not aware if you can directly connect to BRP069A78. Take a look at issues #15 and #27. You can try this maybe this will work https://github.com/speleolontra/daikin_residential_altherma
