### ISSUE TITLE
No climate entiteit 

### ISSUE THREAD

**Issue by Homeassistjoenka** [tadasdanielius/daikin_altherma#71]
How can it that we not climate entiteit have?
![IMG_3900](https://github.com/tadasdanielius/daikin_altherma/assets/113582714/3d37d512-1015-4bc0-844b-6edeb39da360)

**Comment by tadasdanielius** [comment]
The integration does not create a climate entity as the entire control is done by Daikin's thermostat. However, you may have the option to control the desired thermostat temperature with a numeric sensor.

**Comment by Homeassistjoenka** [comment]
Oke Thanks
