### ISSUE TITLE
Thermostat problem 

### ISSUE THREAD

**Issue by homeyjoenka** [tadasdanielius/daikin_altherma#72]
We change the Temp in the thermostat but than change only the state van on to off not change the temp how can we that fix?
![IMG_0514](https://github.com/tadasdanielius/daikin_altherma/assets/61145850/fad4644c-8b42-4999-9ff8-3d739739f9ba)
![IMG_0518](https://github.com/tadasdanielius/daikin_altherma/assets/61145850/84def081-a534-4f09-bb14-e43eca60ae4d)

**Comment by tadasdanielius** [comment]
If you have daikin's thermostat you can change the temperature via sensors but it would not work with generic_thermostat as expected. What you can do is to control the Daikin's thermostat with numeric sensor. When creating generic_thermostat you basically take the whole responsibility of turning on/off device yourself

**Comment by Homeassistjoenka** [comment]
Oké Thanks

**Comment by tadasdanielius** [comment]
ust to add some notes (I am not an expert in heat pumps, just sharing information I read online): I would advise using your heating unit in reference mode. Always keep your device on, especially during the cold season, as turning it off for an extended period and then turning it back on can harm the pump and potentially reduce the lifespan of your device.
Again, I am not an expert, but what I read is that using daikin's thermostat actually consume more energy. 

Generic thermostats are useful if you want to have separate "virtual" thermostats for each room. Personally, I don't have Daikin's thermostat, so I keep the unit on all time. Instead, I have attached valves to the manifold and control each water circuit separately, which gives me the flexibility to independently control the temperature in every room.
