### ISSUE TITLE
Does it work with the wifi gateway BRP069A78 ?

### ISSUE THREAD

**Issue by Jonnehs** [tadasdanielius/daikin_altherma#74]
Hello,

Do you know if the API/integration is available with the wireless gateway BRP069A78 ? I put the IP into your wizard but it didnt work, not sure if that means its not available. The wifi gateway suggests in the app that it does the integrations with google and alexa but I'm not sure if the wired LAN adapter is the only way to access it locally?

**Comment by tadasdanielius** [comment]
To my knowledge, the wireless controller does not have a local API, therefore it does not work with this integration.

**Comment by Jonnehs** [comment]
It does have a web page on its IP, but i cant get to any of the URLs documented and the python api stuff doesn't seem to work

![image](https://github.com/tadasdanielius/daikin_altherma/assets/11739441/d05d1939-4259-490d-87f5-a7b2f9145549)

**Comment by Knutowskie** [comment]
@Jonnehs try this one instead: https://github.com/speleolontra/daikin_residential_altherma

**Comment by tadasdanielius** [comment]
@Jonnehs this issue has been raised few times. It seems that WIFI adapter does not expose any operation list. If you have time you can try to check the profile of the unit.
Go to config / custom_integration / daikin_altherma. Find the file `__init__.py` and change

```python
    # Uncomment this if you want to store profile info in json files.
    #try:
    #    for profile in unit_profiles:
    #        filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
    #        with open(filepath, 'w') as f:
    #            f.write(json.dumps(profile['profile']))
    #except Exception as e:
    #    _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)
```

To

```python
    # Uncomment this if you want to store profile info in json files.
    try:
        for profile in unit_profiles:
            filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
            with open(filepath, 'w') as f:
                f.write(json.dumps(profile['profile']))
    except Exception as e:
        _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)
```
Reboot HA and in your config folder check for files daikin_altherma_*.json
If you see the files and something interesting in it, you can share it here and maybe it is possible to do something about it, but I have my doubts about it.

**Comment by Jonnehs** [comment]
> @Jonnehs this issue has been raised few times. It seems that WIFI adapter does not expose any operation list. If you have time you can try to check the profile of the unit. Go to config / custom_integration / daikin_altherma. Find the file `__init__.py` and change
> 
> ```python
>     # Uncomment this if you want to store profile info in json files.
>     #try:
>     #    for profile in unit_profiles:
>     #        filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
>     #        with open(filepath, 'w') as f:
>     #            f.write(json.dumps(profile['profile']))
>     #except Exception as e:
>     #    _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)
> ```
> 
> To
> 
> ```python
>     # Uncomment this if you want to store profile info in json files.
>     try:
>         for profile in unit_profiles:
>             filepath: str = os.path.join(hass.config.config_dir, f'daikin_altherma_{profile["idx"]}.json')
>             with open(filepath, 'w') as f:
>                 f.write(json.dumps(profile['profile']))
>     except Exception as e:
>         _LOGGER.warning(f'Failed to save profile state to file {filepath}. It does not affect the operation of the integration.', exc_info=True)
> ```
> 
> Reboot HA and in your config folder check for files daikin_altherma_*.json If you see the files and something interesting in it, you can share it here and maybe it is possible to do something about it, but I have my doubts about it.

It doesn't generate any files, suspect the local API isn't presented as you say. Annoying.

Guess I'll order the LAN adapter

**Comment by Dieter4712** [comment]
@Jonnehs 
I'm facing a similar issue and would like to control my heat pump within my local network. Have you purchased a LAN adapter, and did it work for you?

**Comment by tadasdanielius** [comment]
What model is your heatpump?

**Comment by Dieter4712** [comment]
> What model is your heatpump?

It is a Daikin Altherma EBBX11DF9W

Today I ordered a brp069a62 module.

**Comment by tadasdanielius** [comment]
There is something wrong with Daikin's technical support. I checked [Installer reference guide for Daikin Altherma 3 R W](https://www.daikin-ce.com/content/dam/document-library/Installer-reference-guide/heat/air-to-water-heat-pump-low-temperature/erla11-14d/ERLA11-14D(W1.V3).ERLA-D(V37.W17).EBBH-D(6V.9W).EBBX-D(6V.9W)_Installer%20reference%20guide_4PEN643603-1C_English.pdf) and page 29 states that it can be combined.
