### ISSUE TITLE
daikin brp069a62 no details 

### ISSUE THREAD

**Issue by burden42** [tadasdanielius/daikin_altherma#92]
have installed a daikin brp069a62 on to a daikin altherma monblock system with a room thermostat

unit comes on line and is seen by home assistant 

but only the Hot water cylinder is seen and all the sensors are off line   

know issue ?

is it a firmware update required on the daikin brp069a62 if so can not see any firmware on the daikin website 

thankyou

**Comment by lufetico** [comment]
I had the same problem as you for months, but this week I got a firmware update to the gateway and it seems to be solved.

Please install the firmware update proposed by the “ONECTA - Daikin” App. The new version is 436CC180000.

**Comment by burden42** [comment]
Is there a way to get the firmware manually?

**Comment by lufetico** [comment]
It is probably possible, but I don't know how to do it. Maybe in a Daikin developer forum they can help you.

**Comment by lufetico** [comment]
I spoke too soon. Today the integration started to fail again. :(

**Comment by burden42** [comment]
Interesting my daikin updated to day the controller

Not yet tried the lan gateway. This was via the WiFi adapter

**Comment by burden42** [comment]
Contracted Daikin . They advised have another attempt at connecting the adaptor. This time it did 2 firmware updates , and after another power cycle . I now have connections into home assistant 
Daikin adapter on version  436CC180000. 

Apparently firmware is not available to download and install manually

**Comment by burden42** [comment]
See above
