### ISSUE TITLE
Use of deprecated hass.helpers.aiohttp_client which will stop working in HA 2024.11

### ISSUE THREAD

**Issue by MikeEvans** [tadasdanielius/daikin_altherma#93]
Detected that custom integration 'daikin_altherma' accesses hass.helpers.aiohttp_client. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from aiohttp_client directly at custom_components/daikin_altherma/init.py, line 29: session = hass.helpers.aiohttp_client.async_get_clientsession(), please create a bug report at https://github.com/tadasdanielius/daikin_altherma/issues

**Comment by tadasdanielius** [comment]
which version of the integration you are using?

**Comment by 22Pascal** [comment]
doesn t work with BRP069A78 ....Any idea ?

**Comment by MikeEvans** [comment]
> doesn't work with BRP069A78 ....Any idea ?

Did the previous version work? I thought BRP069A78 didn't have the local API

**Comment by 22Pascal** [comment]
It s a new DAIKIN installation (and i use HA 2024 6.2)
Thanks for your response, i ll investigate further on API availability
