### ISSUE TITLE
Request for water flow rate new sensor

### ISSUE THREAD

**Issue by scambian28** [tadasdanielius/daikin_altherma#96]
Hi, I’m using the integration with Daikin Altherma R Hybrid CHYH09AA connected to BRP069A62 running in parallel with Daikin ONECTA integration with no issues. 
I would like to get from the heat pump the information of water flow rate l/m to calculate the COP/SCOP in HA.
This water flow rate information is available on user interface but missing in both HA integrations. 
Would it be possible to get such data in HA?
Thank

**Comment by tadasdanielius** [comment]
Can you see water flow rate l/m in onecta app?

**Comment by scambian28** [comment]
No, in onecta  app is not available. 
I can see it only in the daikin user interface menu 6.1  display sensor info

**Comment by tadasdanielius** [comment]
The LAN adapter does not provide that information, so at the moment it is not possible to retrieve it. If you want to get that data, you should check [ESPAltherma](https://raomin.github.io/ESPAltherma/). With ESPAltherma, you can get much more details as it connects directly to the board.

**Comment by scambian28** [comment]
Thank you Danielius for your support. 
I was looking at ESPAltherma but, at present, I do prefer not to implement  it. 
I appreciate your Integration for my monitoring process because of the data update frequency that seems to be quicker  compared to Daikin ONECTA that is limited by the  the API rate limit.
